package com.xabarin.app.popularmovies.model.movies;

import android.os.Parcel;
import android.os.Parcelable;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * Created by francisco on 8/08/15.
 * Generated by http://www.jsonschema2pojo.org/
 */
public class Movie implements Parcelable {

    //                              ...@ @..
    //                              ..(‘o‘)..
    //                              .º(___)º.
    //    <<< DO NOT MODIFY FIELDS NAMES OR YOU WILL BREAK RETROFIT RESPONSE CALLS!!! >>>

    // Ordering code based on github contributor https://github.com/sockeqwe
    // ===========================================================
    // Final Fields
    // ===========================================================

    // ===========================================================
    // Fields
    // ===========================================================

    private Boolean adult;
    private String backdrop_path;
    private List<Integer> genre_ids = new ArrayList<Integer>();
    private Integer id;
    private String original_language;
    private String original_title;
    private String overview;
    private String release_date;
    private String poster_path;
    private Float popularity;
    private String title;
    private Boolean video;
    private Float vote_average;
    private Integer vote_count;
    private Map<String, Object> additionalProperties = new HashMap<String, Object>();

    // ===========================================================
    // Constructors
    // ===========================================================

    public Movie() {
    }

    public Movie(Parcel in) {
        readFromParcel(in);
    }

    // ===========================================================
    // Getter & Setter
    // ===========================================================

    /**
     * @return The adult
     */
    public Boolean getAdult() {
        return adult;
    }

    /**
     * @param adult The adult
     */
    public void setAdult(Boolean adult) {
        this.adult = adult;
    }

    /**
     * @return The backdrop_path
     */
    public String getBackdrop_path() {
        return backdrop_path;
    }

    /**
     * @param backdrop_path The backdrop_path
     */
    public void setBackdrop_path(String backdrop_path) {
        this.backdrop_path = backdrop_path;
    }

    /**
     * @return The genre_ids
     */
    public List<Integer> getGenre_ids() {
        return genre_ids;
    }

    /**
     * @param genre_ids The genre_ids
     */
    public void setGenre_ids(List<Integer> genre_ids) {
        this.genre_ids = genre_ids;
    }

    /**
     * @return The id
     */
    public Integer getId() {
        return id;
    }

    /**
     * @param id The id
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * @return The original_language
     */
    public String getOriginal_language() {
        return original_language;
    }

    /**
     * @param original_language The original_language
     */
    public void setOriginal_language(String original_language) {
        this.original_language = original_language;
    }

    /**
     * @return The original_title
     */
    public String getOriginal_title() {
        return original_title;
    }

    /**
     * @param original_title The original_title
     */
    public void setOriginal_title(String original_title) {
        this.original_title = original_title;
    }

    /**
     * @return The overview
     */
    public String getOverview() {
        return overview;
    }

    /**
     * @param overview The overview
     */
    public void setOverview(String overview) {
        this.overview = overview;
    }

    /**
     * @return The release_date
     */
    public String getRelease_date() {
        return release_date;
    }

    /**
     * @param release_date The release_date
     */
    public void setRelease_date(String release_date) {
        this.release_date = release_date;
    }

    /**
     * @return The poster_path
     */
    public String getPoster_path() {
        return poster_path;
    }

    /**
     * @param poster_path The poster_path
     */
    public void setPoster_path(String poster_path) {
        this.poster_path = poster_path;
    }

    /**
     * @return The popularity
     */
    public Float getPopularity() {
        return popularity;
    }

    /**
     * @param popularity The popularity
     */
    public void setPopularity(Float popularity) {
        this.popularity = popularity;
    }

    /**
     * @return The title
     */
    public String getTitle() {
        return title;
    }

    /**
     * @param title The title
     */
    public void setTitle(String title) {
        this.title = title;
    }

    /**
     * @return The video
     */
    public Boolean getVideo() {
        return video;
    }

    /**
     * @param video The video
     */
    public void setVideo(Boolean video) {
        this.video = video;
    }

    /**
     * @return The vote_average
     */
    public Float getVote_average() {
        return vote_average;
    }

    /**
     * @param vote_average The vote_average
     */
    public void setVote_average(Float vote_average) {
        this.vote_average = vote_average;
    }

    /**
     * @return The vote_count
     */
    public Integer getVote_count() {
        return vote_count;
    }

    /**
     * @param vote_count The vote_count
     */
    public void setVote_count(Integer vote_count) {
        this.vote_count = vote_count;
    }

    public Map<String, Object> getAdditionalProperties() {
        return this.additionalProperties;
    }

    public void setAdditionalProperty(String name, Object value) {
        this.additionalProperties.put(name, value);
    }


    // ===========================================================
    // Methods from SuperClass/Interfaces
    // ===========================================================

    @Override
    public int describeContents() {
        return 0;
    }

    /**
     * Write only the neccesary data to be sent to the Action Detail
     *
     * @param dest
     * @param flags
     */
    @Override
    public void writeToParcel(Parcel dest, int flags) {
        dest.writeString(getTitle());
        dest.writeString(getPoster_path());
        dest.writeString(getOverview());
        dest.writeFloat(getVote_average());
        dest.writeString(getRelease_date());
    }


    // ===========================================================
    // Methods
    // ===========================================================

    private void readFromParcel(Parcel in) {
        setTitle(in.readString());
        setPoster_path(in.readString());
        setOverview(in.readString());
        setVote_average(in.readFloat());
        setRelease_date(in.readString());
    }

    public static final Parcelable.Creator<Movie> CREATOR =
            new Parcelable.Creator<Movie>() {

                @Override
                public Movie createFromParcel(Parcel in) {
                    return new Movie(in);
                }

                @Override
                public Movie[] newArray(int size) {
                    return new Movie[size];
                }
            };

    // ===========================================================
    // Inner and Anonymous Classes
    // ===========================================================
}
